# Generated by Django 4.2.2 on 2023-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialkey',
            name='used_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
