# Generated by Django 5.0.1 on 2024-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_serialkey_used_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
